#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/wenle/development/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/wenle/Desktop/Workspace/Trans_Prism/Trans_Prism"
export "FLUTTER_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/wenle/Desktop/Workspace/Trans_Prism/Trans_Prism/ios/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/wenle/Desktop/Workspace/Trans_Prism/Trans_Prism/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.5.0"
export "FLUTTER_BUILD_NUMBER=1.5.0"
export "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuNDQuNA==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vbWlycm9ycy50dW5hLnRzaW5naHVhLmVkdS5jbi9naXQvZmx1dHRlci1zZGsuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049YWQ3MGVjNDYxNw==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049YTEwZDhhYzM4ZA==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMi4y"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/wenle/Desktop/Workspace/Trans_Prism/Trans_Prism/.dart_tool/package_config.json"
